nestjs/graphql

lib/graphql-types.loader.ts, lib/graphql.module.ts, package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
```
I've noticed that, after adding the GraphQL module, the time to boot the application increased significantly (about 2000-2300ms in a 4 GHz i7). After some benchmarks, i've noticed that almost all the time was being spent in `graphql-types.loader.ts`.
The current behavior uses the package `glob`, without ignoring `node_modules`, and it reads the types using the function `readFileSync` from `fs`.
After some changes, i was able to improve the time to boot …
=> refactor: improve types merging performance

lib/graphql-ast.explorer.ts
```
[x] Bugfix
[ ] Feature
```
Define GraphQL schemas below
```graphql
type Query {
parent: [Parent]
}
type Parent {
children(limit: Int): [Children]
}
```
See the generated type defs be like
```ts
export abstract class Parent {
abstract children(limit?: number): Children[] | Promise<Children[]>;
}
```
Which causes wrong typing for frontend project using the type defs
```ts
const parent = await client.query<Parent>(gql`
{
parent { children(limit: 10) { ... } }
}
`)
parent.children // Expected array of …
```
=> bugfix() generate types with method only if parent is root

lib/graphql.factory.ts
```
[x] Bugfix
[ ] Feature
```
TS typing generation causes a restart loop with nodemon.
Issue Number: Fixes #136
TS typing generation does not cause a restart loop with nodemon. (Generated file is overwritten only if the content has changed.)
```
[ ] Yes
[x] No
```
=> fix(graphql.factory): prevent typing generation from causing a restart loop with nodemon

lib/decorators/resolvers.decorators.ts
Added missing context to subscription filter method
```
[ ] Bugfix
[x] Feature
```
Issue Number: #165
Subscription filter parameters receive context too.
```
[ ] Yes
[x] No
```
=> Added missing context to subscription filter method

package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: move deps
```
Remove warning:
```
@nestjs/graphql@6.0.5 requires a peer of type-graphql@^0.17.0 but none is installed. You must install peer dependencies yourself.
```
```
[ ] Yes
[x] No
```
=> chore(deps): move type-graphql to optional deps

.gitignore, lib/graphql-ast.explorer.ts, tests/e2e/generated-definitions.spec.ts, tests/generated-definitions/array-property.fixture.ts, tests/generated-definitions/array-property.graphql, tests/generated-definitions/custom-scalar.fixture.ts, tests/generated-definitions/custom-scalar.graphql, tests/generated-definitions/enum.fixture.ts, tests/generated-definitions/enum.graphql, tests/generated-definitions/interface-property.fixture.ts, tests/generated-definitions/interface-property.graphql, tests/generated-definitions/mutation.fixture.ts, tests/generated-definitions/mutation.graphql, tests/generated-definitions/query.fixture.ts, tests/generated-definitions/query.graphql, tests/generated-definitions/simple-type.fixture.ts, tests/generated-definitions/simple-type.graphql
- [n/a] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
`prop: [String!]` currently outputs `prop: string[]` because of the `String!`, which is incorrect because whether `prop` is required is based on whether there is a `!` outside the brackets, not inside.
`prop: [String!]` now outputs `prop?: string[]` instead.
```
[x] Yes
[ ] No
```
Technically this is a breaking change, if there is any `propName: [Foo!]` within a project's graphql schema the outputted …
=> fix(@nestjs/graphql): fix array type output of generated properties

lib/graphql-ast.explorer.ts, lib/graphql-definitions.factory.ts, lib/graphql.factory.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Performance improvement
```
`ts-morph` library is being always loaded, even if type definitions are generated beforehand.
`ts-morph` library will be loaded on demand. If the developer decides to generate typescript definitions beforehand, this change will reduce memory footprint by ~17 MB and will also slightly increase startup performance.
```
[ ] Yes
[x] No
```
=> perf: Lazy load ts-morph

lib/graphql-types.loader.ts
Ever since this repo's switch to fast-glob (in February/March), I've noticed that the generated type files were not consistent between runs. This was particularly problematic when a project had a GraphQL schema split across multiple .graphql files
I suspected it because fast-glob's return value is not deterministic. By sorting the return from fast-glob, the generated type files should have the generated types in a consistent order.
```
[x] Bugfix
[ ] Feature
```
The generated graphql.schema.ts file had …
=> bugfix: Sort file paths for more consistent type output

lib/decorators/subscription.decorator.ts
```
[ ] Bugfix
[x] Feature
```
I added Promise types to subscription decorator because in the docs of [type-graphql](https://typegraphql.ml/docs/subscriptions.html) has support promises.
```
[ ] Yes
[x] No
```
=> feat(subscription.decorator) added promise type to filter&resolver

lib/graphql-types.loader.ts, package-lock.json, package.json
Add in normalize-path package to normalize windows file paths and allow fast-glob to function.
Fix for #331 and #336
- [x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x ] Tests for the changes have been added (for bug fixes / features)
```
[x ] Bugfix
[ ] Feature
```
In a windows environment when using `process.cwd()` the paths come out looking like `C:\\Users\\user\\Documents\\path\\to\\cwd` which is an invalid path for `fast-glob` and …
=> bugfix(@nestjs/graphql): fix windows path

lib/graphql.module.ts, tests/e2e/global-prefix.spec.ts
```
[x] Bugfix
[ ] Feature
```
https://github.com/nestjs/graphql/pull/314/files#r312075349
The `useGlobalPrefix` option will fail if:
- The global prefix does not have starting slash, i.e. `app.setGlobalPrefix('api/v1')`;
- The global prefix has ending slash, i.e. `app.setGlobalPrefix('/api/v1/')`;
Works well.
```
[ ] Yes
[x] No
```
=> fix(): global prefix fails in some cases

lib/graphql.module.ts, tests/e2e/global-prefix.spec.ts, tests/graphql/global-prefix-async-options-class.module.ts, tests/graphql/global-prefix-async-options.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #418
Default options are merged when initializing the module using `GraphQLModule.forRootAsync()`
```
[x] Yes - in theory
[ ] No
```
In theory someone could have be using the current behavior where the global prefix has undefined appended to it and this would break that but I can't imagine anyone would be comfortable using a path like `/api/v1undefined`.
I wasn't sure how to best organize the new tests. Let me know if there is anything with those or the PR …
=> bugfix() merge default options when async configuration

package.json
iterall was imported without being in package.json
This works in some environments because the package steals iterall from its sub dependencies, but it is not a good practice and not compatible with https://yarnpkg.com/lang/en/docs/pnp/ and with upcoming similar features from `npm`
This is a bad practice in general: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md
Fixes https://github.com/nestjs/graphql/issues/537
=> fix(deps): add iterall dependency

lib/graphql-ast.explorer.ts, package-lock.json, package.json
```
[x] Bugfix
[ ] Feature
[x] Build related changes
```
- `npm run build` will fail on Windows because `rm` command is not an executable 
- When we take the schema first approach and use the `GraphQLDefinitionsFactory` to generate the typescript file, it will always use LF line endings, which will cause warnings when using `git add` on Windows
- `npm run build` can run on Windows
- The generated typescript file will have appropriate line endings(CRLF on windows and LF on *nix) 
```
[ ] Yes
[x] No
```
=> Better support on windows

lib/graphql.factory.ts
```
[x] Bugfix
[ ] Feature
```
Methods decorated with `@Subscription` are not copied into the resolvers. As a result, `AsyncIterator` is not returned causing `Subscription field must return Async Iterable. Received: undefined`
Issue Number: 663
References to methods are copied accordingly. Subscribers subscribe to `AsyncIterators` and receive updates.
```
[ ] Yes
[x] No
```
Copying `subscribe()` does not affect any resolvers.
=> fix(): subscription.subscribe() not copied

lib/federation/graphql-federation.module.ts
Extends GraphQL Federation module to use the typeDefs in addition to typePaths. The feature is already available in NestJS GraphQL base module.
```
[ ] Bugfix
[x] Feature
```
```ts
const myTypeDefs = gql`
extend type Query {
...
}
`
GraphQLFederationModule.forRoot({
typePaths: ['./**/*.graphql'],
typeDefs: [myTypeDefs] // Override by typePaths
})
```
```ts
const myTypeDefs = gql`
extend type Query {
...
}
`
GraphQLFederationModule.forRoot({
typePaths: ['./**/*.graphql'],
typeDefs: [myTypeDefs] // Merged with typePaths
})
```
```
[ ] Yes
[x ] No
```
=> GraphQL Federation - typedefs merged with typePaths

lib/interfaces/custom-scalar.interface.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #222 
In strict mode of TypeScript, the current definition of `CustomScalar` doesn't allow us to return `null` or `undefined`.
This code will not throw any errors in strict mode.
```typescript
parseLiteral(ast: any): Date {
if (ast.kind === Kind.INT) {
return new Date(ast.value);
}
return null;
}
```
```
[ ] Yes
[x] No
```
References:
- https://github.com/graphql/graphql-js/blob/278bde0a5cd71008452b555065f19dcd1160270a/src/type/definition.d.ts#L293-L296
- …
=> Fix CustomScalar interface for strictNullChecks

lib/services/resolvers-explorer.service.ts, lib/utils/merge-defaults.util.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #695 #730
1. Middleware + resolvers use the same context id.
2. `ContextIdFactory.getByRequest(this.ctx)` to get the current context id (where `ctx` = `@Inject(CONTEXT)`)
```
[ ] Yes
[ ] No
```
=> feat(): use request context id symbol, attach to ctx

lib/schema-builder/factories/resolve-type.factory.ts
```
[x] Bugfix
[ ] Feature
```
I was messing with Union types when this error appeared. It turned out the actual error message did not return because of a missing undefined check: 
```
TypeError: Cannot read property 'type' of undefined"
at ResolveTypeFactory.<anonymous> 
(.../node_modules/@nestjs/graphql/dist/schema-builder/factories/resolve-type.factory.js:18:28)
```
With this patch the error no longer gets swallowed:
```
Abstract type \"ProjectType\" must resolve to an Object type at runtime for …
```
=> fix: make sure to handle undefined case in ResolveTypeFactory

lib/federation/graphql-federation.module.ts, tests/code-first-federation/post/post.service.ts, tests/e2e/graphql-federation-fastify.spec.ts, tests/e2e/graphql-federation.spec.ts, tests/e2e/graphql-gateway-async-class.spec.ts, tests/e2e/graphql-gateway-async-existing.spec.ts, tests/e2e/graphql-gateway-async.spec.ts, tests/e2e/graphql-gateway-buildservice.spec.ts, tests/e2e/graphql-gateway-fastify.spec.ts, tests/e2e/graphql-gateway.spec.ts, tests/graphql-federation/posts-service/federation-posts.module.ts, tests/graphql-federation/posts-service/posts/posts.service.ts, tests/graphql-federation/posts-service/posts/posts.types.graphql, tests/graphql-federation/posts-service/posts/upper.directive.ts
Update the schema with provided custom directives before initializing the ApolloServer per unique requirements of federated services: https://www.apollographql.com/docs/apollo-server/federation/implementing-services/#defining-custom-directives
Closes #837
- [] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
Custom directives are never loaded for federated GraphQL services.
Issue Number: 837
As defined by Apollo, customer directives are now applied to the schema …
=> bugfix(federated-directives): update federation module directive loading

lib/graphql-ast.explorer.ts, tests/generated-definitions/federation.fixture.ts, tests/generated-definitions/federation.graphql
```
[x] Bugfix
[ ] Feature
```
From [the federation example](), the following _invalid_ typings are generated:
```graphql
type Post @key(fields: "id") {
id: ID!
title: String!
body: String!
user: User
}
extend type User @key(fields: "id") {
id: ID! @external
posts: [Post]
}
extend type Query {
getPosts: [Post]
}
```
```ts
export class Post {
id: string;
title: string;
body: string;
user?: User
}
```
Where a `User` class/interface is not generated 
This PR handles `ObjectTypeExtension` …
=> fix(federation): Handle ObjectTypeExtension

lib/graphql-schema.builder.ts, lib/graphql.factory.ts, lib/interfaces/gql-module-options.interface.ts, tests/e2e/graphql-sort-auto-schema.spec.ts, tests/e2e/graphql-sort-schema.spec.ts, tests/graphql/sort-auto-schema.module.ts, tests/graphql/sort-schema.module.ts, tests/utils/printed-schema.snapshot.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #993 (closes #993)
Providing the `sortSchema` option to the `GraphQLModule` will sort the schema lexicographically.
```
[ ] Yes
[x] No
```
I don't consider this to be a breaking change.
=> feat(): Add sortSchema option

lib/graphql-schema.builder.ts, lib/interfaces/gql-module-options.interface.ts, tests/e2e/graphql-transform-auto-schema-file.spec.ts, tests/graphql/transform-auto-schema-file.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #993 
The `transformSchema` option is now applied when writing a `autoSchemaFile` to the filesystem.
```
[ ] Yes
[x] No
```
=> feat(): Apply transformSchema to autoSchemaFile

lib/graphql-types.loader.ts
```
[ ] Bugfix
[X] Feature
```
GraphQL Schemas from node_modules will be ignored when discovering schemas
Issue Number: https://github.com/nestjs/graphql/issues/966
GraphQL schemas will conditionally include node_modules when discovering schemas as long as one of the paths defined in the `typePaths` config contains `node_modules`.
```
[ ] Yes
[X] No
```
=> feat(): Include graphql schemas from node_modules

lib/decorators/mutation.decorator.ts, lib/decorators/query.decorator.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1087
`@Query()` and `@Mutition()` now have `complexity` options and pass them through to the already existing `addResolverPropertyMetadata()` method. No further changes are required to obtain the desired behavior
```
[ ] Yes
[x] No
```
=> feat(): Complexity options on Query and Mutation

lib/graphql.module.ts
```
[ ] Bugfix
[ ] Feature
```
There is no graceful apollo server shutdown on module destroy. It leads to issues like "tests leaking" in jest.
Graphql module stops apollo server using the destroy hook.
```
[ ] Yes
[x] No
```
=> refactor(): stop apollo server on module destroy

lib/federation/graphql-federation.factory.ts, lib/graphql-definitions.factory.ts, lib/graphql.factory.ts, package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
```
The `graphql-tools` package installed as `devDependencies`, when it should be in `dependencies` as well. For example, it breaks Plug'n'Play with the following error:
```
Error: @nestjs/graphql tried to access graphql-tools, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
Also, `graphql-tools` has several smaller packages within monorepo under `@graphql-tools/*`, but `@nestjs/graphql` imports just `graphql-tools` in some …
=> refactor(): use @graphql-tools monorepo instead of graphql-tools package

lib/graphql-ast.explorer.ts, lib/graphql-definitions.factory.ts, lib/graphql.factory.ts, lib/schema-builder/type-definitions.generator.ts, lib/services/base-explorer.service.ts, lib/services/gql-arguments-host.ts, lib/services/gql-execution-context.ts, lib/services/plugins-explorer.service.ts, lib/utils/async-iterator.util.ts, tests/e2e/generated-definitions.spec.ts, tests/e2e/global-prefix-fastify.spec.ts, tests/e2e/graphql-fastify.spec.ts, tests/e2e/graphql-request-scoped.spec.ts, tests/e2e/request-scoped.spec.ts, tests/generated-definitions/custom-header.fixture.ts, tests/generated-definitions/custom-header.graphql, tests/generated-definitions/custom-scalar-default-type.fixture.ts, tests/generated-definitions/custom-scalar-type-mapping.fixture.ts, tests/generated-definitions/custom-scalar-type-mapping.graphql, tests/utils/introspection-schema.utils.ts
I'd be happy to contribute documentation, but it wasn't obvious to me where to find its source.
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/nestjs/graphql/issues/1248
Adds the following 3 fields to `DefinitionsGeneratorOptions`:
```ts
/**
* If provided, specifies a default generated TypeScript type for custom scalars.
* @default 'any'
*/
defaultScalarType?: string;
/**
* If provided, specifies a mapping of types to use for custom scalars
* @default undefined
*/ …
```
=> Specify generated types for custom scalars

lib/extra/graphql-model-shim.ts
```
[ ] Bugfix
[X] Feature
```
As a user I wish to use the @nestjs/graphql package in the front-end to take advantage of re-using some DTO classes. 
Whilst doing a migration from nest 6 to 7 and replacing instances of `type-graphql` library with the `@nestjs/graphql` library I discovered that the `createUnionType` and `registerEnumType` was not exported. 
This feature simply adds `createUnionType` and `registerEnumType` to the shim list as empty functions.
Similar to this closed …
=> feat: add create union type and register enum type to shim

lib/schema-builder/storages/type-metadata.storage.ts, lib/type-helpers/intersection-type.helper.ts, lib/type-helpers/omit-type.helper.ts, lib/type-helpers/partial-type.helper.ts, lib/type-helpers/pick-type.helper.ts, lib/type-helpers/type-helpers.utils.ts, tests/type-helpers/intersection-type.helper.spec.ts, tests/type-helpers/omit-type.helper.spec.ts, tests/type-helpers/partial-type.helper.spec.ts, tests/type-helpers/pick-type.helper.spec.ts
This closes #1351.
```
[x] Bugfix
[ ] Feature
```
1. `Directive` and `Extensions` decorators does not inherit when using mapped types.
2. Directives metadata applying multiple times
Issue Number: #1351
1. `Directive` and `Extensions` decorators is inherited when using mapped types.
2. Skip adding existing directive metadata
```
[ ] Yes
[x] No
```
=> fix: inherit directive and extensions in type helpers, compile unique directives

lib/graphql-ast.explorer.ts, tests/generated-definitions/array-property.fixture.ts, tests/generated-definitions/custom-header.fixture.ts, tests/generated-definitions/custom-scalar-default-type.fixture.ts, tests/generated-definitions/custom-scalar-type-mapping.fixture.ts, tests/generated-definitions/custom-scalar.fixture.ts, tests/generated-definitions/enum.fixture.ts, tests/generated-definitions/federation.fixture.ts, tests/generated-definitions/interface-property.fixture.ts, tests/generated-definitions/mutation.fixture.ts, tests/generated-definitions/query-skip-args.fixture.ts, tests/generated-definitions/query.fixture.ts, tests/generated-definitions/simple-type.fixture.ts, tests/generated-definitions/typename.fixture.ts
Creates a new type alias `Nullable<T>` which will make a given field nullable
if that field is not required by the schema.
This more accurately models the allowed types for GraphQL since GraphQL will
accept `null` as a valid value when a field is marked as such. Prior to this change,
`null` was not allowed as a value in TypeScript since the generated type definition did not allow it.
Closes #1128
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1128
Nullable fields in the GraphQL schema will correctly be …
=> fix(ast): correctly mark fields as nullable when not required

lib/graphql-base-exception-filter.ts, lib/index.ts, tests/e2e/guards-filters.spec.ts, tests/e2e/pipes.spec.ts
Closes #1053
```
[X] Bugfix
[ ] Feature
```
Exceptions are built by Apollo server engine, and because it doesn't recognizes Nest.js's exceptions, it always returns a generic HTTP 500 error, even for other errors, specifically UNAUTHORIZED. 
Issue Number: #1053 
Exceptions are converted explicitly to an `ApolloError`, possibly to a specific exception (if exists), and then thrown for the Apollo server to catch and format. 
```
[X] Yes
[ ] No
```
This change might cause breakages if clients used to assume …
=> feat(@nestjs/graphql): base exception filter for apollo exceptions

lib/graphql-ast.explorer.ts, lib/graphql-definitions.factory.ts, lib/graphql.factory.ts, tests/e2e/generated-definitions.spec.ts, tests/generated-definitions/enum-as-type.fixture.ts, tests/generated-definitions/enum-as-type.graphql
Add enumsAsTypes option to generate string literal union types instead of enums.
Closes #1557
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1557 
```
[ ] Yes
[x] No
```
=> feat(@nestjs/graphql): add enumsAsTypes to definitions generator options

lib/federation/graphql-federation.module.ts, lib/federation/graphql-gateway.module.ts, lib/graphql.module.ts
Apollo server throws unhandled promise rejection when using fastify adapter, now it awaits for the server to start and then proceeds with the createHandler method
fix issue #1536
```
[x] Bugfix
[ ] Feature
```
Apollo server throws unhandled promise rejection when using fastify adapter
Issue Number: #1536 
registerFastify method awaits for the apollo server to start and then proceeds with the createHandler method
```
[ ] Yes
[x] No
```
=> fix : unhandled promise rejection in registerFastify method

lib/federation/graphql-federation.factory.ts, tests/e2e/graphql-federation-schema-host.spec.ts
GraphqlSchemaHost#schema wasn't assigned after GraphqlFederationModule initialization
resolves nestjs/graphql#1478
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1478 
GraphqlSchemaHost#schema assigned and can be used correctly after GraphqlFederationModule initialization
```
[ ] Yes
[x] No
```
=> fix(federation): assignment GraphqlSchemaHost#schema in factory

lib/schema-builder/factories/interface-definition.factory.ts, lib/schema-builder/factories/union-definition.factory.ts
Most GraphQL implementations support using the `__typename` property to determine the type of an object.
So in addition to looking for a match on instance type, this introduces a fallback to the `__typename` property, when it is set.
If you think this is a valuable addition I will cleanup the PR and make sure to follow the contributing guidelines.
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> Consider __typename property of plain javascript objects for type

lib/utils/merge-defaults.util.ts
Without this, Apollo also listens to termination signals and interferes
with our own attempt at graceful shutdown.
Resolves #1560
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1560 
```
[ ] Yes
[x] No
```
I've put no on breaking changes, but it's worth mentioning. There may be users who have not called `enableShutdownHooks`, but have included the `GraphQL` module and so would currently be receiving some graceful shutdown by accident. If they took this change without calling `enableShutdownHooks` they …
=> fix: Use default of false for stop termination on signals

lib/graphql-definitions.factory.ts, tests/e2e/generated-definitions.spec.ts, tests/generated-definitions/federation-typedef.fixture.ts, tests/generated-definitions/federation-typedef.graphql
```
[ ] Bugfix
[X] Feature
```
https://github.com/nestjs/graphql/issues/1581
Issue Number: 1581
Type Def defined in the generation are correctly merged with defined schema in the typePath
```
[ ] Yes
[X] No
```
This is my first ever PR on a public library, so please take a careful look that I not break something carelessly
=> Allow GraphQLDefinitionsFactory to accept typePaths and typeDef for schema generation via cli.

lib/interfaces/gql-gateway-module-options.interface.ts, lib/utils/transform-schema.util.ts
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Currently, the ts files from `@apollo/federation` and `@apollo/gateway` are being imported directly, hence any stricter configuration to tsconfig.json on the consumer level is being enforced on these ts files from `@apollo/federation` and `@apollo/gateway`.
For example, I have `importsNotUsedAsValues` as `error` in my local tsconfig.json, and even with `skipLibCheck` as `true`, tsc still throw this error:
```
node_modules/@apollo/gateway/src/datasources/types.ts:1:1 - …
```
=> Import d.ts from @apollo/federation and @apollo/gateway instead of ts

lib/graphql.module.ts
```
[z] Bugfix
[ ] Feature
```
With apollo-server-express@^3.0.0, application crashes on init
The reason is [this PR](https://github.com/apollographql/apollo-server/pull/5195)
server.start() is required for apollo-server-core@^3.0.0. 
```
(node:17741) UnhandledPromiseRejectionWarning: Error: You must `await server.start()` before calling `server.applyMiddleware()`
at ApolloServer.assertStarted (/Users/choesumin/Desktop/dev/work/pickk-server/node_modules/apollo-server-express/node_modules/apollo-server-c …
```
=> Add await apolloServer.start() to registerExpress

lib/graphql-ws/graphql-ws-subscription.service.ts, lib/graphql-ws/graphql-ws.exception.ts, lib/graphql-ws/is-graphql-ws-subscription.util.ts, lib/graphql.factory.ts, lib/graphql.module.ts, lib/index.ts, lib/interfaces/gql-module-options.interface.ts, package-lock.json, package.json, tests/subscriptions/app/app.module.ts, tests/subscriptions/app/auth.guard.ts, tests/subscriptions/app/notification.module.ts, tests/subscriptions/app/notification.resolver.ts, tests/subscriptions/app/notification.ts, tests/subscriptions/graphql-ws.spec.ts, tests/subscriptions/subscription-transport-ws.spec.ts, tests/subscriptions/utils/graphql-ws.link.ts, tests/subscriptions/utils/malformed-token.exception.ts, tests/subscriptions/utils/missing-authorization.exception.ts
This could close #1341 for the moment, and provide a way to use `graphql-ws` instead of `subscriptions-transport-ws` without breaking existing NestJS services that already use subscriptions.
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1341 
As described in the issue, the GraphQL module currently relies on `subscriptions-transport-ws`, which has several issues and is being deprecated in favor of `graphql-ws`. Apollo will change the gql-on-ws protocol in the future, but I don't believe …
=> feat: allow custom gql-on-ws protocol for subscriptions

lib/schema-builder/helpers/get-default-value.helper.ts
```
[X] Bugfix
[ ] Feature
```
Currently, a `===` is used, which only works for primitive default values. However, this was failing when using an array of values for a default. I think it is simply easier to use the deep equality check with `lodash`, since you are already have that as a dependency.
```
[ ] Yes
[ ] No
```
=> fix: equality check in getDefaultValue

package.json
```
[x] Bugfix
[ ] Feature
```
`apollo-server-express` and `apollo-server-fastify` are missing from `peerDependencies` even though they're being required:
https://github.com/nestjs/graphql/blob/3b9b3b95952b727519430b85b4f3a4374dab574e/lib/graphql.module.ts#L181-L185
https://github.com/nestjs/graphql/blob/3b9b3b95952b727519430b85b4f3a4374dab574e/lib/graphql.module.ts#L212-L216
This PR adds them as optional peer dependencies in order to keep package managers happy (especially Yarn Modern).
```
[ ] Yes …
```
=> fix(@nestjs/graphql): add missing peer dependencies

lib/graphql-ws/graphql-subscription.service.ts
fixed fatal error when sec-websocket-protocol isn't exists in request headers using graphql-ws
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1731
Server still working when sec-websocket-protocol isn't exist in request header
```
[ ] Yes
[x] No
```
=> fix(@nestjs/graphql): fixed fatal error regarding graphql-ws

packages/graphql/lib/factories/params.factory.ts, packages/graphql/lib/services/gql-execution-context.ts
Issue Number: #1238
Currently, when trying to use a request-scoped provider (that injects graphql context) inside a federation reference resolver, its initiated with a wong context instance due to the fact that reference resolvers are invoked with only 3 arguments. That's because `__resolveReference` isn't a `GraphQLFieldResolver`, it's a `GraphQLReferenceResolver` ([as defined in @apollo/subgraph](https://github.com/apollographql/federation/blob/947948f9fd37a64ec3b08d181ffa0c9fd7bda223/subgraph-js/src/schemaExtensions.ts#L3)).
```typescript
import { Inject, Injectable, Scope } from '@nestjs/common'
import { CONTEXT } from '@nestjs/graphql'
@Injectable({ scope: Scope.REQUEST })
export …
```
=> fix(graphql): Fix federation reference resolver context args

packages/apollo/tests/code-first/cats/cats.module.ts, packages/apollo/tests/code-first/cats/cats.resolver.ts, packages/apollo/tests/e2e/resolver-registration-methods.spec.ts, packages/graphql/lib/services/resolvers-explorer.service.ts, packages/mercurius/tests/code-first/cats/cats.module.ts, packages/mercurius/tests/code-first/cats/cats.resolver.ts, packages/mercurius/tests/e2e/resolver-registration-methods.spec.ts
Registration of a class marked with the Resolver() decorator fails silently when trying to pass the class to the providers array in a provider wrapper (e.g. { useFactory(){ ... } } or { useClass: ... })
This PR replaces #1733 and addresses issue #1700 
Issue Number: #1700 
Classes marked with the Resolver decorator behave in a way consistent with how classes marked with the Injectable decorator behave. You can provide a resolver by passing a reference to the class, a wrapper that specifies useFactory, a wrapper that specifies useClass or a wrapper that specifies useValue.
N/A
=> fix(graphql): allow resolvers to be registered in provider wrappers

packages/graphql/lib/graphql.factory.ts, packages/graphql/lib/interfaces/gql-module-options.interface.ts
Issue Number: #2036 
Add an option to inherit the interface resolver's field resolver when an object's field is missing.
=> feat(): Add inheritResolversFromInterfaces property

packages/apollo/package.json, yarn.lock
Workspace `@nestjs/apollo` is missing dependency `tslib`.
Yarn berry (because berry is checking dependency tree) is throwing following error:
```
Error: @nestjs/apollo tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: tslib
```
`tslib` is added into  `@nestjs/apollo` `package.json` file.
=> build: add tslib dependency to the @nestjs/apollo package

packages/graphql/lib/factories/params.factory.ts, packages/graphql/lib/services/gql-execution-context.ts, packages/graphql/lib/utils/normalize-resolver-args.ts
Importing a request scoped provider in a Resolver that defines a `__resolveType` decorated with `@ResolveField()` wrongly creates multiple provider instances in a single request, this is because a resolveType function has not the same arguments as a normal field resolver function (it is missing the `arg` argument), thus the request id used to keep track of the request is wrongly stored in the `info` object instead of the `context` object.
https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/services/resolvers-explorer.service.ts#L170
This PR adds an `undefined` argument where the `args` object should be for `__resolveType` field resolvers
=> fix: resolve type context args in request scoped providers

packages/graphql/lib/services/gql-subscription.service.ts
Follow-up on https://github.com/nestjs/graphql/pull/2145:
Update the `GqlSubscriptionServiceOptions` configuration to allow passing custom `execute()` and `subscribe()` function.
This change is required to support GraphQL Server plugin systems such as [Envelop](https://envelop.dev/) and to allow support [GraphQL Yoga](https://github.com/dotansimha/graphql-yoga).
=> feat(services/gql-subscription): allow custom `execute()` and `subscribe()` for other plugin systems

packages/apollo/package.json
Updated the peer dependency in `@nestjs/apollo` to allow for a peer dependency of `@apollo/gateway` at version in the v2.x.x range while keeping backward compatibility with the 0.x.x releases.
Current peer dependency does not follow the new semver release of `@apollo/gateway`.
Peer dependency now follows the v2.x.x releases of `@apollo/gateway`
=> chore(deps): update `@apollo/gateway` peer dependency

packages/graphql/package.json
```
npm WARN Could not resolve dependency:
npm WARN peerOptional @apollo/subgraph@"^0.1.5 || ^0.3.0 || ^0.4.0" from @nestjs/graphql@10.0.10
npm WARN node_modules/@nestjs/graphql
npm WARN   @nestjs/graphql@"^10.0.10" from the root project
npm WARN   1 more (@nestjs/apollo)
```
Allows usage of `@apollo/subgraph` version `2.0.x` which supports federation v2 spec and is backwards compatible with federation v1
=> Support using @apollo/subgraph 2.0.x

packages/apollo/lib/drivers/apollo-gateway.driver.ts
A custom ApolloServerPlugin annotated with @Plugin is not registered in the the Apollo Gateway driver.
Plugins are now added in options.server.plugins of the ApolloGatewayDriver
=> fix(apollo): add global plugins for apollo gateway driver

packages/graphql/lib/index.ts, packages/graphql/lib/schema-builder/index.ts
Hi @kamilmysliwiec,
In the motivation to implement the GraphQL Yoga Driver in a separate repository (previous discussion: #2145), we need the following exports to be available outside of the package for testing purposes: `GRAPHQL_SDL_FILE_HEADER` (schema generation test), `FileSystemHelper` (mocking for schema DSL file loading).
Example of an Apollo test that won't work if moved outside of this monorepo:
https://github.com/nestjs/graphql/blob/42704556db2e492b218a98091d97bfb3bbca607f/packages/apollo/tests/e2e/graphql-sort-auto-schema.spec.ts#L1-L8
=> fix(graphql): required exports for testing

packages/graphql/lib/services/resolvers-explorer.service.ts
The [resolvers-explorer.service](https://github.com/nestjs/graphql/blob/890762d532c3824037fcfc2c1ef81c653bbd14e7/packages/graphql/lib/services/resolvers-explorer.service.ts#L175) currently isn't using the ContextIdFactory#getByRequest method to retrieve the contextId from the request. Instead, it is manually checking the gqlContext object and calling the createContextId() function. This is a problem if we plan to monkeypatch the ContextIdFactory to create the separate Dependency Trees.
Now we get the `contextId` from `ContextIdFactory#getByRequest()`, passing `req` as a property to be checked.
=> refactor(graphql): use context id factory

packages/graphql/lib/services/resolvers-explorer.service.ts, packages/graphql/lib/utils/function-utils.ts, packages/graphql/lib/utils/index.ts
[resolvers-explorer.service](https://github.dev/nestjs/graphql/blob/671c713455cb80568b1e60b44ad260e6c68c0bf9/packages/graphql/lib/services/resolvers-explorer.service.ts#L334) is wrongly fetching the number of arguments of the `ContextIdFactory#getByRequest` method, relying on the function's length. This returns an invalid number in cases where we have a default parameter (in the [new implementation](https://github.com/nestjs/nest/blob/1ba99cc6d0ec7b01f0eeab2ccbf0ed6c61b4261a/packages/core/helpers/context-id-factory.ts#L30), we have the second parameter as optional, so it returns "1" as the length).
Now we correctly assert the number of arguments to decide the outcome …
=> fix(graphql): get number of arguments

packages/graphql/lib/utils/get-number-of-arguments.util.ts, packages/graphql/tests/utils/function.utils.spec.ts
`getNumberOfArguments` utility function wasn't returning the correct number for edge cases:
1. When using arrays or objects as default arguments
2. When a function had multi-line declaration (the \n character wasn't being captured by regex)
3. When the function's parameters ended with a comma
The function now works correctly for aforementioned cases.
=> test(graphql): add function utils test

packages/graphql/lib/type-helpers/intersection-type.helper.ts, packages/graphql/tests/plugin/type-helpers/intersection-type.helper.spec.ts
Issue Number: #1420
`IntersectionType`
Fix @Field of List type in IntersectionType.
Previously array wrapper was ignored and GraphQL List wrapper was not applied:
```typescript
// [String] was interpreted as String
@Field(() => [String])
```
In suggested changes `IntersectionType` executes type function to support GraphQL List types.
Other helpers (`PickType`, `OmitType`) are using same approach.
Previous PR (#1420) executed type functions eagerly, so could not be merged.
Furthermore it was abandoned more than a year ago, closed for commenting and modification.
=> fix(graphql): Support @Field of list type in IntersectionType

packages/apollo/tests/code-first/recipes/ingredients.resolver.ts, packages/apollo/tests/code-first/recipes/models/ingredient.ts, packages/apollo/tests/code-first/recipes/recipes.module.ts, packages/apollo/tests/e2e/code-first-schema.spec.ts, packages/apollo/tests/utils/printed-schema.snapshot.ts, packages/graphql/lib/schema-builder/storages/type-metadata.storage.ts
Issue Number: #2331
Field options from model base classes are used when a `ResolveField()` is defined for those fields.
=> fix(code-first): Use base model field options with ResolveField()

packages/apollo/tests/e2e/generated-definitions.spec.ts, packages/apollo/tests/generated-definitions/federation-partial-query.fixture.ts, packages/apollo/tests/generated-definitions/federation-partial-query.graphql, packages/graphql/lib/federation/graphql-federation-definitions.factory.ts
Fixes #2344 
Issue Number: #2344 
As described in the issue, `GraphQLFederationDefinitionsFactory` emits duplicate IQuery interface.
This is caused by `buildSubgraphSchema`, which fills empty Query definition when there is no original  `type Query` definition and there is `extend type Query` definition.
Duplicate IQuery interface will be merged.
=> fix(schema-first): merge duplicate IQuery interface

packages/graphql/lib/services/gql-subscription.service.ts
We have a shared Nest server, which serves both Next.js and nestjs/graphQL.
GraphQL WS server conflicts and aborts requests to Next.js, sending to path - "/_next/webpack-hmr".
Next version is 12.2.3.
Nextjs WS server looks like has such path check on its side -
https://github.com/vercel/next.js/blob/0f99768f9811fdf027a083471bd2a435f6207f4a/packages/next/server/dev/next-dev-server.ts#L638-L645
The "nestjs/graphql" package will upgrade listeners only for its path and won't conflict.
=> fix: Restrict subscriptions WS server to add listeners only to its own path

packages/graphql/lib/plugin/visitors/model-class.visitor.ts, packages/graphql/tests/plugin/fixtures/create-cat.dto.ts
Fields in Args are not generated  by the graphQL typescript plugin
Issue Number: https://github.com/nestjs/graphql/pull/1757#issuecomment-1234388563
Fields in Args are generated  by the graphQL typescript plugin
=> fix(@nestjs/graphql): Fix generation of ArgsType metadata

packages/apollo/tests/jest-e2e-fed2.ts, packages/apollo/tests/jest-e2e.ts, packages/graphql/tests/jest-e2e.json, packages/mercurius/tests/jest-e2e.ts
Jest 29 changed the config schema to no longer use `globals` with `ts-jest`. The `test:e2e` script fails with type issues.
This PR fixes the configs to longer fail on our `test:e2e` script.
=> test: fix jest config for jest 29

packages/graphql/lib/schema-builder/errors/cannot-determine-input-type.error.ts
=> fix(graphql): fix word spacing of error message when null

packages/graphql/lib/interfaces/build-schema-options.interface.ts, packages/graphql/lib/schema-builder/errors/multiple-fields-with-same-name.error.ts, packages/graphql/lib/schema-builder/factories/root-type.factory.ts, packages/graphql/tests/schema-builder/factories/root-type.factory.spec.ts
Closes #2143
Issue Number: #2134
A new `buildSchemaOptions` field `noDuplicateFields` is added.
If it is set to `true`, an error is thrown when defining a Query/Mutation field multiple times
=> feat(graphql): Throw an error when multiple resolvers define the same field

packages/apollo/tests/code-first/other/sample-scalar.ts, packages/apollo/tests/e2e/code-first-schema.spec.ts, packages/apollo/tests/utils/printed-schema.snapshot.ts, packages/graphql/lib/schema-builder/graphql-schema.factory.ts
`makeExecutableSchema` throws if a resolver is defined without being present in the schema. We should include scalars even if they're not used by any field (yet)
If an app uses GraphQL code-first schema generation and had a scalar without referencing this from any resolver, the app will throw an error upon startup: `Error: "XYZ" defined in resolvers, but not in schema`
Issue Number: #2255 
Always include scalars in the generated schema by explicitly adding them to the list of types, instead of relying on the implicit inclusion via a resolver in- or output.
N/A
=> fix(@nestjs/graphql): always add scalars to generated schema

packages/graphql/package.json
Yarn PnP doesn't implicitly inherit transitive peer dependencies class-validator and class-transformer from @nestjs/mapped-types. Therefore @nestjs/mapped-types doesn't see class-validator/class-transform and doesn't inherit their metadata.
Similar to: https://github.com/nestjs/swagger/issues/2169
Specify class-validator and class-transformer as optional dependencies.
=> fix(graphql): type helpers metadata inheriting

packages/graphql/lib/federation/type-defs-federation2.decorator.ts, packages/graphql/lib/interfaces/schema-file-config.interface.ts
Imports 4 additional Apollo Federation 2 directives to help ensure the generated `_service` `sdl` is fully Apollo Federation 2.0 spec compatible.
- [`@tag`](https://www.apollographql.com/docs/federation/federated-types/federated-directives#tag)
- [`@inaccessible`](https://www.apollographql.com/docs/federation/federated-types/federated-directives#inaccessible)
- [`@extends`](https://www.apollographql.com/docs/federation/federated-types/federated-directives#extends)
- [`@provides`](https://www.apollographql.com/docs/federation/federated-types/federated-directives#provides)
=> feat(federation): Update the Apollo Federation 2 `@link` imports

packages/apollo/tests/code-first/recipes/dto/new-recipe.input.ts, packages/apollo/tests/code-first/recipes/dto/recipes.args.ts, packages/apollo/tests/code-first/recipes/recipes.resolver.ts, packages/apollo/tests/e2e/code-first-schema.spec.ts, packages/apollo/tests/utils/printed-schema.snapshot.ts, packages/graphql/lib/schema-builder/factories/input-type.factory.ts, packages/graphql/lib/schema-builder/factories/output-type.factory.ts, packages/graphql/lib/schema-builder/services/type-mapper.service.ts
When a not-nullable field has a defaultValue it generates a nullable input field:
```typescript
@InputType()
export class AcmeInput {
@Field({ nullable: false, defaultValue: 'foo' })
bar: string;
}
```
it generates:
```gql
input AcmeInput {
bar: String = "foo"
}
```
The above will generate this schema:
```gql
input AcmeInput {
bar: String! = "foo"
}
```
Some of the tests (e.g. the snapshots) capture the erroneous functionality, so to keep this PR specific to the change, some existing fields had `nullable: true` set to match the existing tests.
=> fix: enable non-nullable, defaulted fields in code-first schema

packages/apollo/package.json, packages/mercurius/package.json
The `@netsjs/apollo` and `@nestjs/mercurius` packages rely on using `loadPackage('@apollo/subgraph')` but this package isn't reflected in either's package.json. This is incompatible with `pnpm`.
=> fix(@nestjs/apollo): Add in missing peer dependencies.

packages/apollo/lib/utils/async-iterator.util.ts, packages/apollo/tests/subscriptions/async-iterator.spec.ts
As https://github.com/apollographql/graphql-subscriptions/pull/209 saids, a filter function that returns mostly false can cause loops in Promises. This leads to a memory leak.
Relevant Issue: https://github.com/apollographql/graphql-subscriptions/issues/212
Applied changes of above PR to existing function `createAsyncIterator`.
Now it does not stack up awaiting Promises.
Credit to. @urossmolnik
=> fix(graphql): prevent potential memory leak for mostly falsy filter function

packages/mercurius/lib/drivers/mercurius-federation.driver.ts, packages/mercurius/lib/drivers/mercurius-gateway.driver.ts, packages/mercurius/lib/drivers/mercurius.driver.ts, packages/mercurius/lib/interfaces/index.ts, packages/mercurius/lib/interfaces/mercurius-driver-config.interface.ts, packages/mercurius/lib/interfaces/mercurius-gateway-driver-config.interface.ts, packages/mercurius/lib/interfaces/mercurius-plugin.interface.ts, packages/mercurius/lib/utils/register-mercurius-plugin.util.ts, packages/mercurius/lib/utils/validation.util.ts, packages/mercurius/tests/e2e/code-first-plugin.spec.ts, packages/mercurius/tests/e2e/graphql-federation-plugin.spec.ts, packages/mercurius/tests/e2e/graphql-gateway-plugin.spec.ts, packages/mercurius/tests/plugins/code-first-plugin/app.module.ts, packages/mercurius/tests/plugins/code-first-plugin/dogs/dogs.module.ts, packages/mercurius/tests/plugins/code-first-plugin/dogs/dogs.resolver.ts, packages/mercurius/tests/plugins/code-first-plugin/main.ts, packages/mercurius/tests/plugins/graphql-federation-plugin/gateway/gateway.module.ts, packages/mercurius/tests/plugins/graphql-federation-plugin/posts-service/federation-posts.module.ts, packages/mercurius/tests/plugins/graphql-federation-plugin/users-service/federation-users.module.ts, packages/mercurius/tests/plugins/mocks/interfaces/plugin-options.interface.ts, packages/mercurius/tests/plugins/mocks/interfaces/plugin-response.interface.ts, packages/mercurius/tests/plugins/mocks/mock.plugin.ts, packages/mercurius/tests/plugins/mocks/utils/constants.ts, packages/mercurius/tests/plugins/mocks/utils/plugin-response.ts
There is no plugins options on the Mercurius Adapter.
Adds a plugins option, to be precise an array of the new `MercuriusPlugin` interface.
So this is an update version of an old [PR](https://github.com/nestjs/graphql/pull/2106), what is different:
- Renamed `MercuriusDriverPlugin` to `MercuriusPlugin`;
- Removed repeated files in tests;
- Removed state from drivers (`delete options.plugins`);
- Uses `for of` instead of a normal for loop for readability.
=> feat(mercurius): add plugins option

packages/graphql/lib/schema-builder/collections/field-directive.collection.ts, packages/graphql/tests/schema-builder/storages/field-directive.collection.spec.ts
Similar directive sdls on multiple fields fail if applied to the same target. I stumbled upon this while migrating from NestJS 8 to 9. It still baffles me how this could have happened from all the code I analysed and read, but I guess there's a good underlying reason for this bug.
I ran into a problem in which the following code doesn't not register all applied directives:
```ts
@Resolver(() => TypeSomething)
export class TwoResolversWithSimilarDirectives {
@Query((returns) => TypeSomething)
@Directive('@hasPermission(permissions: APP_ACCOUNTS_READ)')
@Directive('@limit')
async resolver1() {
return {}
}
@Query((returns) => TypeSomething)
@Directive('@hasPermission(permissions: APP_ACCOUNTS_READ)')
@Directive('@limit')
async resolver2() {
return …
```
=> fix(graphql): similar directive sdls on multiple fields fail

packages/apollo/tests/code-first-duplicate-resolvers/app.module.ts, packages/apollo/tests/code-first-duplicate-resolvers/module-a/module-a.module.ts, packages/apollo/tests/code-first-duplicate-resolvers/module-a/user.resolver.ts, packages/apollo/tests/code-first-duplicate-resolvers/module-b/module-b.module.ts, packages/apollo/tests/code-first-duplicate-resolvers/module-b/user.resolver.ts, packages/apollo/tests/code-first-duplicate-resolvers/query.resolver.ts, packages/apollo/tests/duplicate-resolvers/app.module.ts, packages/apollo/tests/duplicate-resolvers/duplicate-resolver.graphql, packages/apollo/tests/duplicate-resolvers/module-a/module-a.module.ts, packages/apollo/tests/duplicate-resolvers/module-a/user.resolver.ts, packages/apollo/tests/duplicate-resolvers/module-b/module-b.module.ts, packages/apollo/tests/duplicate-resolvers/module-b/user.resolver.ts, packages/apollo/tests/e2e/duplicate-resolvers.spec.ts, packages/graphql/lib/services/resolvers-explorer.service.ts, packages/mercurius/tests/code-first-duplicate-resolvers/app.module.ts, packages/mercurius/tests/code-first-duplicate-resolvers/module-a/module-a.module.ts, packages/mercurius/tests/code-first-duplicate-resolvers/module-a/user.resolver.ts, packages/mercurius/tests/code-first-duplicate-resolvers/module-b/module-b.module.ts, packages/mercurius/tests/code-first-duplicate-resolvers/module-b/user.resolver.ts, packages/mercurius/tests/code-first-duplicate-resolvers/query.resolver.ts, packages/mercurius/tests/duplicate-resolvers/app.module.ts, packages/mercurius/tests/duplicate-resolvers/duplicate-resolver.graphql, packages/mercurius/tests/duplicate-resolvers/module-a/module-a.module.ts, packages/mercurius/tests/duplicate-resolvers/module-a/user.resolver.ts, packages/mercurius/tests/duplicate-resolvers/module-b/module-b.module.ts, packages/mercurius/tests/duplicate-resolvers/module-b/user.resolver.ts, packages/mercurius/tests/e2e/duplicate-resolvers.spec.ts
The resolver metadata cache currently uses the resolver name for the key as shown below
https://github.com/nestjs/nest/blob/39ec4cda7363aac3551ff0f1b83feb41ba2f0bf6/packages/core/helpers/handler-metadata-storage.ts#L60-L63
This causes issues if we have two resolvers in different modules but with the same name and identical method signatures. For controllers, each controller gets a unique ID that is used as the key in the cache as shown below:
https://github.com/nestjs/nest/blob/39ec4cda7363aac3551ff0f1b83feb41ba2f0bf6/packages/core/injector/module.ts#L461-L462
Add code to set up unique IDs for resolvers as well so that cache retrieval is correct.
Issue Number: #1907
Each resolver gets …
=> fix(@nestjs/graphql): set unique ids on resolvers to fix cache errors

packages/apollo/tests/code-first-duplicate-resolvers/app.module.ts, packages/apollo/tests/duplicate-resolvers/app.module.ts, packages/mercurius/lib/drivers/mercurius-federation.driver.ts, packages/mercurius/lib/drivers/mercurius-gateway.driver.ts, packages/mercurius/lib/drivers/mercurius.driver.ts, packages/mercurius/lib/interfaces/mercurius-driver-config.interface.ts, packages/mercurius/lib/interfaces/mercurius-gateway-driver-config.interface.ts, packages/mercurius/lib/interfaces/mercurius-hook.interface.ts, packages/mercurius/lib/utils/register-mercurius-hooks.util.ts, packages/mercurius/tests/e2e/base-hooks-array.spec.ts, packages/mercurius/tests/e2e/base-hooks.spec.ts, packages/mercurius/tests/e2e/gateway-hooks.spec.ts, packages/mercurius/tests/hooks/base-array/graphql.config.ts, packages/mercurius/tests/hooks/base-array/hooks.module.ts, packages/mercurius/tests/hooks/base/graphql.config.ts, packages/mercurius/tests/hooks/base/hooks.module.ts, packages/mercurius/tests/hooks/cats/cats.module.ts, packages/mercurius/tests/hooks/cats/cats.resolver.ts, packages/mercurius/tests/hooks/gateway/graphql.config.ts, packages/mercurius/tests/hooks/gateway/hooks.module.ts, packages/mercurius/tests/hooks/mocks/logger.mock.ts, packages/mercurius/tests/subscriptions/app/app.module.ts, packages/mercurius/tests/subscriptions/subscriptions.spec.ts
There is no way to add [Mercurius Hooks](https://mercurius.dev/#/docs/hooks) into the Mercurius GraphQL Driver
Adds an optional object with the possible hooks that can be added to mercurius.
=> feat(mercurius): add mercurius hooks

packages/graphql/lib/graphql-ast.explorer.ts, packages/graphql/tests/graphql-ast.explorer.spec.ts
Fields with arguments are usually resolved using a separate method with the `@ResolveField()` annotation.
Having such field generated as a _required_ property thus proves quite cumbersome as it forces setting a value for this field in the result of parent `@Query()` method.
Fields with arguments are always generated as optional.
Using `/dev/null` as argument to `explore` looks unfortunate to me, please advise for a better solution.
=> fix(graphql): generate fields as optional when they contain arguments

packages/graphql/lib/decorators/field.decorator.ts, packages/graphql/lib/interfaces/base-type-options.interface.ts, packages/graphql/lib/interfaces/return-type-func.interface.ts, packages/graphql/lib/interfaces/type-options.interface.ts, packages/graphql/tests/plugin/decorators/field.decorator.spec.ts
Currently, when using `@Field(() => MyType, { defaultValue: ... })`, the `defaultValue` type is not checked as `MyType` at compile time. It can lead to runtime errors if you refactor `MyType` but forget to update the default value.
When using the `@Field(() => MyType, { defaultValue: ... })` or the array one `@Field(() => [MyType], { defaultValue: ... })`, the `defaultValue` type is checked and there is a Typescript error if it's not `MyType` or `MyType[]` respectively.
The feature is not available when using `@Field({ defaultValue: ... })`, it defaults to the current behavior of allowing `any` value. 
I think it doesn't, given there is an any fallback, but I may need to test more …
=> feat(types): Type check Field defaultValue

packages/graphql/lib/federation/type-defs-federation2.decorator.ts, packages/graphql/lib/interfaces/schema-file-config.interface.ts
When using code-first solution, `nest-js/graphql` module will auto import Federation v2.0 directives. Federation spec is evolving and additional `@composeDirective` and `@interfaceObject` were added in the subsequent minor versions.
Users can explicitly add new directives but it is an unnecessary extra step
```javascript
GraphQLModule.forRoot<ApolloFederationDriverConfig>({
driver: ApolloFederationDriver,
autoSchemaFile: {
federation: {
version: 2,
directives: [
'@composeDirective',
'@extends',
'@external',
'@inaccessible',
'@interfaceObject',
'@key',
'@override',
'@provides',
'@requires',
'@shareable',
'@tag',
],
importUrl: 'https://specs.apollo.dev/federation/v2.3'
}
}
}),
``` 
Issue …
=> feat(federation): Update Apollo Federation v2.3 `@link` imports

packages/graphql/lib/schema-builder/collections/metadata-by-name.collection.ts
When creating a field resolver with an input we reached a bad edge case where the fields array was fetched via reference instead of an immutable array. This caused artifacts appearing in the array and bad metadata appeared when trying to parse the schema.
Returning a new array from the metadata instead of the reference for the existing array solves this issue
https://github.com/nestjs/graphql/issues/2360#issuecomment-1475362011
Issue Number: 2360
Fields resolver works correctly.
=> fix: metadata storage refactor caused a bug in field resolver

packages/graphql/lib/decorators/object-type.decorator.ts, packages/graphql/lib/schema-builder/metadata/class.metadata.ts
Currently there is no way to inherit the description from generic `ObjectType` marked with `isAbstract`. Which means for every new `ObjectType` that extends a generic we need to reuse the description from somewhere else in order to have a tidy documentation.
Introduces a new `inheritDescription` option to `ObjectTypeOptions`, when set to `true`, direct descendant classes will inherit the parent's description if own description is not set.
=> feat(graphql): Allow ObjectType to inherit description

packages/graphql/lib/plugin/utils/plugin-utils.ts
Compilation fails on Windows in certain cases when using the GraphQL plugin because absolute paths are prefixed with `./`.
Issue Number: #2661
Don't prefix absolute paths on Windows with `./`.
I think this is a temporary solution at best. I'm not sure the `posix` version of `path` methods should be being used for all the logic in the plugin, since things like `posix.relative()` do not behave properly with windows paths. I could maybe create another pull request to switch to the non-posix path methods, but not sure if I'm missing an important reason it's in use.
I also wanted to add a test but it's tricky:
```ts
describe('plugin-utils', () => {
describe('replaceImportPath', () => { …
```
=> fix(plugin): don't prefix absolute win paths

packages/apollo/package.json
Set `@apollo/subgraph` as an optional peer dependency in `@nestjs/apollo`
`@apollo/subgraph` should only be needed if using Apollo Federation/Apollo Gateway.
`@apollo/subgraph` is installed regardless if you are using Apollo Federation or not
By setting `@apollo/subgraph` to optional those that are relying it being installed as a non-optional peer dependency will need to install it in their packages.
`@apollo/subgraph` is already correctly set as an optional peer dependency in `@nestjs/graphql`: https://github.com/nestjs/graphql/blob/master/packages/graphql/package.json#L56-L58
=> chore(deps): set @apollo/subgraph as optional

packages/graphql/lib/decorators/args.decorator.ts, packages/graphql/lib/decorators/field.decorator.ts, packages/graphql/lib/decorators/mutation.decorator.ts, packages/graphql/lib/decorators/query.decorator.ts, packages/graphql/lib/decorators/resolve-field.decorator.ts, packages/graphql/lib/decorators/subscription.decorator.ts, packages/graphql/lib/interfaces/base-type-options.interface.ts, packages/graphql/lib/interfaces/type-options.interface.ts
Cannot set defaultValue to null value for `@Field` decorator with `{nullable: true}` option.
```
class User {
@Field(() => String, { nullable: true, defaultValue: null }) # Type 'null' is not assignable to type 'String | undefined'.ts(2322)
name!: string | null;
}
```
Issue Number: https://github.com/nestjs/graphql/issues/2995
Can set defaultValue to null value for `@Field` decorator with `{nullable: true}` option.
=> fix(graphql): Set defaultaValue type nullable

packages/apollo/tests/e2e/__snapshots__/serialized-graph.spec.ts.snap, packages/graphql/lib/schema-builder/factories/args.factory.ts, packages/graphql/lib/schema-builder/factories/ast-definition-node.factory.ts
(not convinced this is needed for that, and no test already exists for it)
(same as previous)
Currently, a directive on a argument is entirely ignored and not run nor detected (I'm thinking specifically of fields in ArgsType classes).
Directives are properly detected and applied, even when using on arguments from ArgsType classes.
=> fix(graphql): fix directives on arguments

packages/graphql/lib/type-helpers/partial-type.helper.ts, packages/graphql/tests/plugin/type-helpers/partial-type.helper.spec.ts
This allows removing defaultValue for the optional properties. It doesn't make much sense to have a nullable field in an update dto that has a default value.
PartialType does keep defalutValue option. It doesn't make much sense to have a nullable field in an update dto that has a default value.
Issue Number: #1425
A new option is added (omitDefaultValue) that allows removing the defaultValue.
Also the current second argument (decorator) is converted into a optionsOrDecorator argument.
The old behaviour is kept by default, so this is not a breaking change.
=> feat(graphql): Add omitDefaultValue option to PartialType

packages/graphql/lib/type-helpers/partial-type.helper.ts
- [1 ] Bugfix
The current issue with the partial type utility function in NestJS/GraphQL arises from the absence of a proper assignment of decorator variable when passed as a ClassDecoratorFactory.
Consider both scenarios: ClassDecoratorFactory and PartialTypeOptions.
=> fix: fixed assigning decorator when passed as class decorator factory

packages/graphql/lib/federation/graphql-federation.factory.ts
The option for resolverValidationOptions isn't being passed along to addResolversToSchema despite it being included in graphql federation options and it being supported by addResolversToSchema.
Related to https://github.com/nestjs/graphql/pull/2994
Support resolverValidationOptions for schema first federation
=> feat(graphql): support resolverValidationOptions for schema first federation

packages/apollo/tests/e2e/graphql-sort-auto-schema.spec.ts, packages/apollo/tests/graphql/sort-auto-schema.module.ts, packages/graphql/lib/graphql-schema.builder.ts, packages/graphql/lib/graphql.constants.ts, packages/graphql/lib/interfaces/build-schema-options.interface.ts
Issue Number: #2732
Added new option `addNewlineAtEnd` to `BuildSchemaOptions`, which appends a newline at the end of the generated GraphQL SDL file when set to `true`. If the option is set to `false` or omitted, the SDL file will be generated without adding an extra newline at the end.
This option is applicable only in the code-first approach.
=> feat(graphql): add support for option newline at the end of schema file

packages/graphql/lib/graphql-schema.builder.ts
The `scalarsMap` in `buildSchemaOptions` was not used even though it was defined.
This PR also fixes issues like #3204 by correctly merging the `scalarsMap`, ensuring that duplicate `ScalarsTypeMap` entries are ignored by their `type`. e.g.
```ts
buildSchemaOptions: {
numberScalarMode: 'integer',
scalarsMap: [
{
type: Date,
scalar: GraphQLDateTime,
},
],
}
```
This PR ensures that the `scalarsMap` in `buildSchemaOptions` is respected and correctly merged with the `scalarsMap` from `ScalarsExplorerService`.
=> fix(graphql): ensure scalarsMap in buildSchemaOptions is respected

packages/graphql/lib/decorators/args.decorator.ts, packages/graphql/lib/schema-builder/factories/args.factory.ts, packages/graphql/lib/schema-builder/metadata/param.metadata.ts
The official document said that @Args option allowed deprecationReason, but it did not. GraphQL allows deprecation directives for arguments, so I made it allow deprecationReason.
Issue Number: #3033 
I make changes to AuthorResolver of https://github.com/bodil-dev/nest-graphql-args-deprecated . Because, deprecated arguments required nullable or default value. (see https://spec.graphql.org/draft/#sec--deprecated)
And I add `@ArgsType` usage.
Then, `@deprecated` will be given properly.
=> fix(graphql): add deprecationReason to ArgsOptions

packages/graphql/lib/interfaces/gql-module-options.interface.ts, packages/graphql/lib/schema-builder/metadata/union.metadata.ts, packages/graphql/lib/type-factories/create-union-type.factory.ts
Added `debug` and `introspection` in `GqlModuleOptions`. Added relevant jsDocs for improved developer experience. Closes #3142 
Issue Number: #3142 
Auto-complete will now work in supported editors and developers will have an idea what `debug` and `introspection` are without referring to nest/apollo docs.
=> docs(graphql): added jsdoc for debug and introspection. closes #3142

packages/graphql/lib/graphql-ast.explorer.ts
In the generated typescript (schema-first), classes and interfaces for types are upper cased, but remained in the original case when referenced in method arguments and return types.
This is a fix for this.
Issue Number: #3147
=> fix(graphql): fix case of generated method return and parameter types

packages/graphql/lib/type-helpers/partial-type.helper.ts, packages/graphql/tests/plugin/type-helpers/partial-type.helper.spec.ts
Adding the same skipNullProperties as this PR https://github.com/nestjs/swagger/pull/2863/files added for the Swagger version of PartialType. Original feature coming from this Mapped-Type PR https://github.com/nestjs/mapped-types/pull/1274
PartialType can optionally return a class for which validations are ignored only for undefined properties, not null properties. This can be useful if you are creating a DTO for a mutation endpoint: there may be a certain field, say name, that should not be null, but which doesn't need to be included in updates.
=> feat(@nestjs/graphql): add support for skipNullProperties in PartialType

packages/apollo/lib/drivers/apollo-base.driver.ts
The code in error extensions is INTERNAL_SERVER_ERROR if we set HttpStatus.UNPROCESSABLE_ENTITY for ValidationPipe. 
```json
{
"errors": [
{
"extensions": {
"code": "INTERNAL_SERVER_ERROR",
}
}
]
}
```
The code in error extensions is BAD_USER_INPUT.
```json
{
"errors": [
{
"extensions": {
"code": "BAD_USER_INPUT",
}
}
]
}
```
Can we have it merged please or there is some reason why this mapping was not added before?
=> feat(apollo): map unprocessable entity code to bad user input

packages/graphql/lib/schema-builder/storages/type-metadata.storage.ts
The former logic was accessing the inherited metadata factory, I guess when the current class didn't have one.
The parent class could have fields that the plugin cannot determine, and are explicitly declared with `@Field` decorators.
The partial info & the type from decorator are merged together for that base type.
But here when the subclass was redefining this field it only had partial info, no type.
This caused the complication logic to fail, because the `typeFn` would be missing.
Instead, we only want to look for the _own_ metadata factory, and ignore if there is none.
Just to note: inherited fields are merged elsewhere (in factories), so this doesn't need to try. …
=> fix(graphql): avoid partial field declarations from inherited metadata with cli plugin

packages/graphql/lib/graphql-ast.explorer.ts
Issue Number: #3210
Reinforce the `DefinitionsGeneratorOptions.defaultTypeMapping` interface for better visual over the allowed types.
> Better suggestions over the supported types
>
> ![Screenshot 2024-10-24 at 11 39 58 PM](https://github.com/user-attachments/assets/09ff069f-f86c-4fad-b9b5-fedb016bd996)
>
> ![Screenshot 2024-10-24 at 11 41 07 PM](https://github.com/user-attachments/assets/98a22025-520d-4c62-87c7-bec99751abdb)
> will close #3210
=> refactor(graphql/lib): definitions generator `defaultTypeMapping` type reinforcement

packages/graphql/lib/utils/generate-token.util.ts, packages/graphql/package.json, yarn.lock
The `crypto` global is available in all supported Node.js versions as well as [in all major browsers](https://caniuse.com/mdn-api_crypto_randomuuid). The uuid module is rendered unnecessary for uuidv4.
`@nestjs/graphql` is currently downloaded about 580000 times per week, so about 30740000 times per year. `uuid@11` is about 3.7 kB in size (gzipped+minified). Removing this dependency saves about 113GB traffic per year.
=> chore(deps): Use `crypto.randomUUID()` instead of `uuid` module

packages/apollo/tests/e2e/code-first-inheritance.spec.ts, packages/graphql/lib/schema-builder/storages/type-metadata.storage.ts
GraphQL Schema can be compiled only once. If it happens twice, if the schema relies on abstract absolvers, they will lack important metadata, e.g. query/mutation arguments.
See https://github.com/nestjs/graphql/issues/2657 for more information.
When compiling the schema, raw metadata (coming from decorators) is separated out from the compiled metadata (that is later used to build the final schema).
Fixes https://github.com/nestjs/graphql/issues/2657 .
=> fix: separate raw and compiled resolver metadata from each other

packages/graphql/lib/schema-builder/storages/type-definitions.storage.ts
This PR adds a function to get all union types from the type definitions storage. So far, this function has been missing. We need this for a generation use case involving the type definitions storage. In this case, we want to get _all_ definitions, not just object, interface, input.
=> chore: add function to get all union defs

packages/apollo/lib/drivers/apollo-federation.driver.ts
Currently all subscriptions are disabled when using the apollo federation driver. There is no reason to disable them, they work perfectly fine, and even though Apollo's GraphOS is an enterprise offering, solutions such as [Wundergraph Cosmo](https://wundergraph.com) can use them. 
Issue Number: 
https://github.com/nestjs/graphql/issues/2879
https://github.com/nestjs/nest/issues/11987
and many others
Now we allow subscriptions to function just like the existing Apollo Driver. 
I know this is an absolute dealbreaker for my own org, and based on the responses in the linked issues, i'm sure many other people feel the same way. 
If the maintainer will allow such a change, I can continue making some tests / etc. I have verified that doing this change results in a perfectly operable subgraph …
=> Allow subscriptions in the apollo federation driver

packages/apollo/lib/drivers/apollo-base.driver.ts
After upgrading to Apollo Server v5 `@nestjs/apollo` requires you to install `@as-integrations/express5`, otherwise is throws an error. The `@as-integrations/express5` is not needed when the package is used together with Fastify.
Issue Number: #3693
`@nestjs/apollo` allows for the consumer to use Fastify instead of Express
=> fix(@nestjs/apollo): lazy-load the Express dependency to allow the Fastify usage
