lib/graphql.factory.ts
```
[x] Bugfix
[x] Feature
```
Pre-supplied schema is rendered useless.
Issue Number: https://github.com/nestjs/graphql/issues/49
Schemas will be merged if supplied.
```
[x] Yes
[] No
```
Type conflicts and resolutions are not implemented yet.
=> Merge schema from options if available

lib/graphql-ast.explorer.ts, lib/graphql.factory.ts, lib/interfaces/gql-module-options.interface.ts, package.json
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> release: 5.5.0 minor relase

lib/graphql.module.ts, lib/interfaces/gql-module-options.interface.ts, package-lock.json, package.json, tests/e2e/global-prefix.spec.ts, tests/graphql/global-prefix.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: Closes #142 
Adds a new option called `useGlobalPrefix?: boolean` which is available on `GqlModuleOptions`
```
[ ] Yes
[x] No
```
Implementation inspired by https://github.com/nestjs/terminus/pull/261
=> Add useGlobalPrefix option

lib/decorators/args.decorator.ts, lib/decorators/mutation.decorator.ts, lib/decorators/query.decorator.ts, lib/decorators/resolver.decorator.ts, lib/decorators/resolvers.utils.ts, lib/decorators/subscription.decorator.ts, package-lock.json, package.json
I'm assuming these are all fine. I just removed a dependency, but it shouldnt require any changes in tests/docs
```
[x] Bugfix
[ ] Feature
```
Removed the `optional` package dependency. Was causing issues with ncc/webpack. 
https://github.com/nestjs/nest/issues/2213
Issue Number: 2213
Projects running on Zeit Now will not be able to use graphql + type-graphql, as the require calls don't function properly when transpiled
Transpiler is now able to statically analyze the require calls to type-graphql
``` …
```
=> Removing  `optional` dependency

lib/graphql.constants.ts, tests/generated-definitions/custom-scalar.fixture.ts
```
[ ] Bugfix
[x] Feature
```
ESLint is not ignored.
ESLint ignored.
```
[ ] Yes
[x] No
```
=> feat(typings generation): eslint-disable

lib/utils/generate-token.util.ts
Update new usage for `uuid@v7`.
```
[ ] Bugfix
[ ] Feature
```
The console prints out warning message: `DeprecationWarning: Deep requiring like const uuidv4 = require('uuid/v4'); is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.`
No more warning message
```
[ ] …
```
=> refactor(): update usage for uuid@v7

lib/plugin/visitors/model-class.visitor.ts
```
[x] Bugfix
[ ] Feature
```
Current map of properties is always cached at compiling time so some changes like HideField decorator and nullable option etc would not affect anymore at second time restart
Issue Number: 668
Changes were applied to schema as expected after restart
```
[ ] Yes
[x] No
```
=> bugfix(): some changes not correctly applied

lib/graphql-ast.explorer.ts, lib/graphql-definitions.factory.ts, lib/graphql.factory.ts, lib/interfaces/gql-module-options.interface.ts, tests/e2e/generated-definitions.spec.ts, tests/generated-definitions/query-skip-args.fixture.ts, tests/generated-definitions/typename.fixture.ts, tests/generated-definitions/typename.graphql
```
[ ] Bugfix
[x] Feature
```
Issue Number: #410 #744
```
[ ] Yes
[x] No
```
=> feat(): add additional definitions generator options

lib/decorators/field.decorator.ts, lib/decorators/resolve-field.decorator.ts, lib/interfaces/complexity.interface.ts, lib/interfaces/index.ts, lib/schema-builder/factories/object-type-definition.factory.ts, lib/schema-builder/factories/root-type.factory.ts, lib/schema-builder/metadata/property.metadata.ts, lib/schema-builder/metadata/resolver.metadata.ts, lib/schema-builder/storages/type-metadata.storage.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #672 
```
[ ] Yes
[x] No
```
=> feat(): add complexity feature

lib/utils/merge-defaults.util.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(): assign req to object instead of object merge #830

lib/schema-builder/index.ts, lib/schema-builder/storages/index.ts
- [X ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[X ] Feature
```
Right now we can access to the type metadata storage
Issue Number: https://github.com/nestjs/graphql/issues/842
The type metadata storage instance now is exposed
```
[ ] Yes
[X ] No
```
=> feat(): expose type metadata storage instance

tests/code-first/recipes/models/category.ts, tests/code-first/recipes/recipes.resolver.ts, tests/e2e/code-first-schema.spec.ts, tests/e2e/code-first.spec.ts, tests/utils/printed-schema.snapshot.ts
… it being considered nullable when it shouldnt be
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test(): show regression of defaultValue not providing defaultValue 

lib/type-helpers/omit-type.helper.ts, lib/type-helpers/pick-type.helper.ts, tests/type-helpers/omit-type.helper.spec.ts, tests/type-helpers/pick-type.helper.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: Fixes #1153
```
[ ] Yes
[x] No
```
Not sure if this is a breaking change or not. In theory it is, but the behavior was broken in the first place.
=> fix(): mapped types with renamed fields

lib/schema-builder/factories/object-type-definition.factory.ts, tests/code-first/recipes/models/recipe.ts
Also update tests to test this behavior.
Fixes https://github.com/nestjs/graphql/issues/1136
- Docs have been added / updated (for bug fixes / features)
☝️ I didn't see anywhere to add docs in this repo
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1136 
```
[ ] Yes
[x] No
```
=> fix(): Fix handling of multi-level interfaces

lib/extra/graphql-model-shim.ts
~I don't see a place fit for documenting this feature in this repo, except in the file itself. I could mention it [https://docs.nestjs.com/graphql/other-features](here), ill start working on that soon.~
Edit: Added docs in the docs repo, PR [here.](https://github.com/nestjs/docs.nestjs.com/pull/1505)
```
[ ] Bugfix
[x] Feature
```
Issue Number: Closes #1082
Allows overriding import with shim file in order to nullify decorator effects in models shared with the frontend.
```
[ ] Yes
[x] No
```
=> Feat: added model shim file

lib/schema-builder/factories/enum-definition.factory.ts, lib/schema-builder/metadata/enum.metadata.ts, lib/type-factories/register-enum-type.factory.ts, tests/code-first/enums/direction.enum.ts, tests/e2e/code-first-schema.spec.ts, tests/utils/printed-schema.snapshot.ts
```
[ ] Bugfix
[x] Feature
```
Closes #1126 
Enum values may be marked as deprecated by providing a `deprecationReasons` key in the `EnumOptions` argument of `registerEnumType()`.
```
[ ] Yes
[x] No
```
=> feat(): Add support for enum value deprecation and description

lib/interfaces/field-middleware.interface.ts
```
[ ] Bugfix
[ ] Feature
[x ] Other... Type change
```
Related to this issue: https://github.com/nestjs/graphql/issues/1507
=> fix(@nest/graphql): change FieldMiddleware context type

lib/services/resolvers-explorer.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1468 
```
[ ] Yes
[x] No
```
=> fix: disable enhancers for __resolveType

lib/interfaces/build-schema-options.interface.ts, lib/schema-builder/factories/orphaned-types.factory.ts, lib/schema-builder/storages/type-definitions.storage.ts, lib/schema-builder/storages/type-metadata.storage.ts, tests/code-first/enums/sample-orphaned.enum.ts, tests/e2e/code-first-schema.spec.ts, tests/utils/printed-schema.snapshot.ts
```
[ ] Bugfix
[x] Feature
```
Allow adding an enum to a schema output using `orphanedTypes`
(need docs update)
Issue Number: #1665 
```
[ ] Yes
[x] No
```
=> feat(schema-builder): allow enums for `orphanedTypes`

packages/graphql/lib/schema-builder/factories/resolve-type.factory.ts
=> fix(graphql): resolve type function should not always be async

packages/apollo/tests/generated-definitions/array-property.fixture.ts, packages/apollo/tests/generated-definitions/array-property.graphql, packages/graphql/lib/graphql-ast.explorer.ts
Issue Number: https://github.com/nestjs/graphql/issues/2091
=> fix(graphql): support nested arrays when generating type defs

packages/graphql/lib/type-helpers/partial-type.helper.ts
~- [ ] Tests for the changes have been added (for bug fixes / features)~
Incorrect spelling
n/a
n/a
=> docs: fix typo

packages/mercurius/package.json, yarn.lock
=> Revert "chore(deps): update dependency mercurius to v10"

packages/mercurius/lib/utils/build-mercurius-federated-schema.util.ts
fixes #2364
Issue Number: #2364
=> refactor: remove lodash usage

packages/graphql/lib/schema-builder/factories/interface-definition.factory.ts
Literally copy/pasted from `ObjectDefinitionFactory`.
Issue Number: #2374
=> fix(): Merge in parent interface fields to interfaces

LICENSE, README.md
Updated logo in readme and update license
=> chore(): updated logo in readme and update license 

packages/mercurius/lib/interfaces/mercurius-gateway-driver-config.interface.ts
So there when rebasing I added a typo on the Gateway, so it does not have all the possible gateway hooks
=> fix(mercurius): gateway hooks typo

packages/apollo/package.json, packages/mercurius/package.json
Attempting to use new `@nestjs/apollo` v11 package complains about broken peer dependencies:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nestjs/apollo@11.0.2
npm ERR! Found: @nestjs/graphql@11.0.0
npm ERR! node_modules/@nestjs/graphql
npm ERR!   @nestjs/graphql@"^11.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/graphql@"^10.1.7" from @nestjs/apollo@11.0.2
npm ERR! node_modules/@nestjs/apollo
npm ERR!   @nestjs/apollo@"^11.0.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @nestjs/graphql@10.2.0
npm ERR! node_modules/@nestjs/graphql
npm ERR!   peer …
```
=> chore: update peer deps to @nestjs/graphql v11

packages/graphql/lib/plugin/utils/ast-utils.ts
Fixing issue: https://github.com/nestjs/graphql/issues/2800.
It's a very straightforward PR.
=> [#2800] Fix graphql schema generation with plugin introspectComments enabled

packages/graphql/lib/graphql.module.ts, packages/graphql/lib/interfaces/gql-module-options.interface.ts, packages/graphql/lib/plugin/compiler-plugin.ts, packages/graphql/lib/plugin/index.ts, packages/graphql/lib/plugin/merge-options.ts, packages/graphql/lib/plugin/metadata-loader.ts, packages/graphql/lib/plugin/utils/is-filename-matched.util.ts, packages/graphql/lib/plugin/utils/plugin-utils.ts, packages/graphql/lib/plugin/visitors/model-class.visitor.ts, packages/graphql/lib/plugin/visitors/readonly.visitor.ts
=> feat(plugin): introduce readonly visitors

packages/graphql/lib/federation/graphql-federation.factory.ts
Resolves fields on interface level for schema first federation. Similar to this PR, but for federation
=> feat(): support inheritResolversFromInterfaces for schema first federation

package.json, yarn.lock
Add @types/supertest
Typescript can not resolve `request.post` on `*.spec.ts` files  because of missing type definition for Supertest
Resolve type definitition for `supertest`.
=> chore(deps): Add @types/supertest

packages/mercurius/lib/drivers/mercurius-gateway.driver.ts, packages/mercurius/package.json, yarn.lock
Issue Number: 
Proposal:
- Upgrade to `Mercurius` v14.x 🔥 
- Upgrade to `@mercuriusjs/gateway` v3
- Upgrade to `@mercuriusjs/federation` v3
It closes the following PR:
- https://github.com/nestjs/graphql/pull/3195
- https://github.com/nestjs/graphql/pull/3196
- https://github.com/nestjs/graphql/pull/3197
=> feat(mercurius): upgrade to mercurius v14

packages/apollo/tests/code-first-federation/app.module.ts, packages/apollo/tests/code-first-federation/human/character.entity.ts, packages/apollo/tests/code-first-federation/human/human.entity.ts, packages/apollo/tests/code-first-federation/human/human.module.ts, packages/apollo/tests/code-first-federation/human/human.resolver.ts, packages/apollo/tests/e2e/__snapshots__/code-first-federation.spec.ts.snap, packages/apollo/tests/e2e/code-first-federation.spec.ts, packages/graphql/lib/federation/graphql-federation.factory.ts
When use `ApolloFederationDriver` in GraphQLModule, interface resolvers is not working
https://docs.nestjs.com/graphql/interfaces#interface-resolvers 
Interface resolvers works for `ApolloFederationDriver`
=> fix(apollo): federation interface resolver

packages/graphql/lib/graphql-definitions.factory.ts, packages/graphql/package.json, yarn.lock
extra 11 dependencies
11 dependencies less, better TypeeScript support
E2E tests pass. maybe worth adding a `is-glob` to filter out non-glob inputs and not wrap them in a glob?
=> chore: upgrade chokidar to v4
